<?php

namespace CoreSys\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlashRepository extends EntityRepository
{
}
